# Generated by Django 4.2.16 on 2024-10-22 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upgrade_type', models.TextField()),
                ('work_type', models.TextField()),
                ('env_ip_map', models.TextField(default='{}')),
            ],
        ),
    ]
