# Generated by Django 4.2.16 on 2024-12-08 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='设备名称')),
                ('ip_address', models.CharField(max_length=15, verbose_name='IP地址')),
                ('device_type', models.CharField(max_length=50, verbose_name='设备类型')),
                ('rack_number', models.CharField(max_length=50, verbose_name='机架编号')),
                ('position', models.IntegerField(verbose_name='机架位置')),
                ('status', models.CharField(max_length=20, verbose_name='设备状态')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
            ],
            options={
                'verbose_name': '设备',
                'verbose_name_plural': '设备列表',
                'ordering': ['rack_number', 'position'],
            },
        ),
        migrations.CreateModel(
            name='DeviceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='device_images/')),
                ('model_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('model_config', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, unique=True, verbose_name='机架编号')),
                ('row', models.IntegerField(verbose_name='排号')),
                ('column', models.IntegerField(verbose_name='列号')),
                ('total_units', models.IntegerField(default=42, verbose_name='总单元数')),
            ],
            options={
                'verbose_name': '机架',
                'verbose_name_plural': '机架列表',
                'ordering': ['row', 'column'],
            },
        ),
        migrations.AlterField(
            model_name='build',
            name='ne_ip_input',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='RackConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rack_number', models.CharField(max_length=50)),
                ('position', models.IntegerField()),
                ('device_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config_api.devicetype')),
            ],
        ),
    ]
