# Generated by Django 4.2.16 on 2024-12-08 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config_api', '0002_device_devicemodel_devicetype_rack_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicetype',
            name='model_config',
        ),
        migrations.AddField(
            model_name='devicetype',
            name='model_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='config_api.devicetype', verbose_name='设备类型'),
        ),
    ]
